// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace efPower.Models;

public partial class Event
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime Date { get; set; }

    public int Categeory { get; set; }

    public string Details { get; set; }

    public DateTime CreationDate { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public int Visibility { get; set; }

    public int ViewerNum { get; set; }

    public int TotalMoney { get; set; }

    public int ParticipantsNumb { get; set; }

    public DateTime SoldOut { get; set; }

    public string Place { get; set; }

    public string Url { get; set; }

    public int Payment { get; set; }

    public int OrgId { get; set; }

    public virtual ICollection<Feature> Features { get; set; } = new List<Feature>();

    public virtual User Org { get; set; }

    public virtual ICollection<PrivateQuestion> PrivateQuestions { get; set; } = new List<PrivateQuestion>();

    public virtual ICollection<Ticketet> Ticketets { get; set; } = new List<Ticketet>();
}