// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace efPower.Models;

public partial class Feature
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int Price { get; set; }

    public int ParticipateNumber { get; set; }

    public int Limit { get; set; }

    public int EventId { get; set; }

    public virtual Event Event { get; set; }

    public virtual ICollection<Ticketet> Ticketts { get; set; } = new List<Ticketet>();
}