// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace efPower.Models;

public partial class PrivateQuestion
{
    public string Question { get; set; }

    public int EventId { get; set; }

    public virtual Event Event { get; set; }
}