// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace efPower.Models;

public partial class Ticketet
{
    public int Id { get; set; }

    public DateTime SubscriptionTime { get; set; }

    public int UserId { get; set; }

    public int EventId { get; set; }

    public virtual Event Event { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<Feature> Features { get; set; } = new List<Feature>();
}