// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace efPower.Models;

public partial class User
{
    public int Id { get; set; }

    public string Fname { get; set; }

    public string Lname { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int Role { get; set; }

    public string Phone { get; set; }

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    public virtual ICollection<Ticketet> Ticketets { get; set; } = new List<Ticketet>();
}